# Generated by Django 3.1.7 on 2021-03-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('noticia', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
