# Generated by Django 3.1.7 on 2021-03-31 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportes',
            name='categ',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='noticias.categorias'),
        ),
    ]
