# Generated by Django 3.1.7 on 2021-03-31 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_deportes_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronavirus',
            name='categ',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='noticias.categorias'),
        ),
        migrations.AddField(
            model_name='famosos',
            name='categ',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='noticias.categorias'),
        ),
        migrations.AddField(
            model_name='internacionales',
            name='categ',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='noticias.categorias'),
        ),
        migrations.AddField(
            model_name='nacionales',
            name='categ',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='noticias.categorias'),
        ),
    ]
