# Generated by Django 3.1.7 on 2021-04-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20210331_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famosos',
            name='categ',
        ),
        migrations.RemoveField(
            model_name='coronavirus',
            name='categ',
        ),
        migrations.RemoveField(
            model_name='deportes',
            name='categ',
        ),
        migrations.RemoveField(
            model_name='internacionales',
            name='categ',
        ),
        migrations.RemoveField(
            model_name='nacionales',
            name='categ',
        ),
        migrations.DeleteModel(
            name='categorias',
        ),
        migrations.DeleteModel(
            name='famosos',
        ),
    ]
