# Generated by Django 3.1.7 on 2021-04-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coronavirus',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='deportes',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='internacionales',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='nacionales',
            name='imagen',
        ),
    ]
